import { useState, useEffect } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Lock, CheckCircle, AlertCircle } from 'lucide-react';
import { useFlutterwave, closePaymentModal } from 'flutterwave-react-v3';
import { Button } from '../components/ui/Button';
import { supabase } from '../lib/supabase';
import { useToast } from '../context/ToastContext';

export function Payment() {
  const navigate = useNavigate();
  const { toast } = useToast();
  const location = useLocation();
  const { formData } = location.state || {};
  const [isProcessing, setIsProcessing] = useState(false);
  const [status, setStatus] = useState<'idle' | 'verifying' | 'generating' | 'error'>('idle');
  const [errorMessage, setErrorMessage] = useState('');
  console.log("status", status)
  console.log("isProcessing", isProcessing)

  useEffect(() => {
    // Check if we have form data, if not redirect to Create
    if (!formData) {
      navigate('/create');
    }

    // Check if user is logged in
    supabase.auth.getSession().then(({ data: { session } }) => {
      if (!session) {
        // Redirect to login if not authenticated
        // In a real app we'd want to preserve the formData
        toast('Please log in to continue', 'error');
        navigate('/login');
      }
    });
  }, [formData, navigate]);

  const config = {
    public_key: import.meta.env.VITE_FLUTTERWAVE_PUBLIC_KEY,
    tx_ref: Date.now().toString(),
    amount: 5000,
    currency: 'NGN',
    payment_options: 'card,mobilemoney,ussd',
    customer: {
      email: 'user@example.com', // In real app, get from auth user
      phone_number: '',
      name: formData?.partnerName || 'Valued Customer',
    },
    customizations: {
      title: 'Amour Love Letter',
      description: 'Unlock your personalized masterpiece',
      logo: 'https://st2.depositphotos.com/4403291/7418/v/450/depositphotos_74189661-stock-illustration-online-shop-log.jpg',
    },
  };

  const handleFlutterwavePayment = useFlutterwave(config);

  const handleSuccess = async (response: any) => {
    closePaymentModal();

    if (response.status === 'successful') {
      setStatus('verifying');

      try {
        // Refresh session to ensure we have a valid token
        const { data: { session }, error: sessionError } = await supabase.auth.refreshSession();
        if (sessionError || !session) {
          throw new Error("Session expired. Please sign in again.");
        }

        console.log("Current Session Token:", session.access_token);

        // Call our Edge Function
        const { data, error } = await supabase.functions.invoke('verify-payment', {
          body: {
            transaction_id: response.transaction_id,
            prompt_data: formData
          }
        });
        console.log("supabaseResponseData", data)
        console.log("supabaseResponseError", error)

        if (error) {
          console.log(error);
          if (error.code === 401 || error.context?.status === 401) {
            throw new Error("Authentication failed. Please sign out and sign in again.");
          }
          throw error;
        }

        if (data && (data.error || data.success === false)) {
          throw new Error(data.error || "Payment verification failed backend");
        }

        navigate('/result', { state: { letter: data.letter } });
      } catch (err: any) {
        console.error(err);
        setErrorMessage(err.message || JSON.stringify(err));
        setStatus('error');
      }
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center px-6 bg-[#FFF5F5]">
      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        className="w-full max-w-lg bg-white p-8 rounded-3xl shadow-xl shadow-[#8B1E3F]/5 border border-[#E5E5E5]"
      >
        <div className="text-center mb-8">
          <div className="w-16 h-16 bg-[#FFF0F5] rounded-full flex items-center justify-center mx-auto mb-6 text-[#8B1E3F]">
            <Lock className="w-8 h-8" />
          </div>
          <h2 className="text-3xl font-serif text-[#2A2A2A] mb-2">Unlock Your Love Letter</h2>
          <p className="text-[#666]">
            Your masterpiece is ready to be generated by our advanced AI.
          </p>
        </div>

        <div className="bg-[#FAFAFA] rounded-xl p-6 mb-8 border border-[#E5E5E5]">
          <div className="flex justify-between items-center mb-4 pb-4 border-b border-[#E5E5E5]">
            <span className="font-medium text-[#2A2A2A]">Love Letter Generation</span>
            <span className="font-bold text-[#2A2A2A]">₦5,000.00</span>
          </div>
          <div className="flex items-center text-sm text-[#666]">
            <CheckCircle className="w-4 h-4 text-[#8B1E3F] mr-2" />
            AI-Enhanced Writing (Gemini Pro)
          </div>
        </div>

        {status === 'error' && (
          <div className="bg-red-50 text-red-600 p-4 rounded-xl mb-6 flex flex-col items-start">
            <div className="flex items-center mb-2">
              <AlertCircle className="w-5 h-5 mr-2" />
              <span className="font-medium">Verification Failed</span>
            </div>
            <p className="text-sm opacity-90">{errorMessage || 'Something went wrong generating your letter.'}</p>
            <p className="text-xs mt-2 text-gray-500">
              Note: This usually happens if the Backend Function "verify-payment" is not deployed to Supabase.
            </p>

            <button
              onClick={async () => {
                await supabase.auth.signOut();
                window.location.href = '/login';
              }}
              className="mt-4 px-4 py-2 bg-red-100 text-red-700 rounded-lg text-sm font-medium hover:bg-red-200 transition-colors"
            >
              Sign Out & Retry
            </button>
          </div>
        )}

        {status === 'verifying' ? (
          <div className="text-center py-8">
            <div className="animate-spin w-8 h-8 border-4 border-[#8B1E3F] border-t-transparent rounded-full mx-auto mb-4"></div>
            <p className="text-[#8B1E3F] font-medium">Crafting your letter...</p>
          </div>
        ) : (
          <Button
            size="lg"
            className="w-full"
            onClick={() => {
              handleFlutterwavePayment({
                callback: handleSuccess,
                onClose: () => {console.log("closed")},
              });
            }}
          >
            Pay Now
          </Button>
        )}

        <p className="text-center text-xs text-[#999] mt-6">
          Secured by Flutterwave
        </p>
      </motion.div>
    </div>
  );
}